name: Java CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: 'Download latest JDK 17'
      run: |
        wget \
          --no-verbose \
          --directory-prefix $RUNNER_TEMP \
          https://download.oracle.com/java/17/archive/jdk-17.0.12_linux-x64_bin.tar.gz

    - name: 'Set up JDK'
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: jdkfile
        jdkFile: ${{ runner.temp }}/jdk-17_linux-x64_bin.tar.gz

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: obfuscator.jar
        path: obfuscator-core/target/obfuscator-core-1.9.3-SNAPSHOT.jar
